#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/cjs/puppeteer/node/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/cjs/puppeteer/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/cjs/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/cjs/puppeteer/node/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/cjs/puppeteer/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/cjs/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/lib/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules/puppeteer/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/puppeteer@24.38.0_typescript@5.9.3/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../lib/cjs/puppeteer/node/cli.js" "$@"
else
  exec node  "$basedir/../../lib/cjs/puppeteer/node/cli.js" "$@"
fi
