#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/lib/cjs/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/lib/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/lib/cjs/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/lib/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules/@puppeteer/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/@puppeteer+browsers@2.13.0/node_modules:/root/nmd-multi-market-platform/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/lib/cjs/main-cli.js" "$@"
else
  exec node  "$basedir/../../../../../@puppeteer+browsers@2.13.0/node_modules/@puppeteer/browsers/lib/cjs/main-cli.js" "$@"
fi
