// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9SMx7a_UI5feRfuDUwfamMm7Vxul6PQ',
    appId: '1:457325133463:web:664ea8965a76ea02b0f3d2',
    messagingSenderId: '457325133463',
    projectId: 'now-market-59841',
    authDomain: 'now-market-59841.firebaseapp.com',
    storageBucket: 'now-market-59841.firebasestorage.app',
    measurementId: 'G-PRQYT6NNSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVasrjeARlkwCtAL0zM2WcZ11s77IIbb8',
    appId: '1:457325133463:android:e8c945f722350148b0f3d2',
    messagingSenderId: '457325133463',
    projectId: 'now-market-59841',
    storageBucket: 'now-market-59841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3YzMwetvXB-1JNB2kHdb8RaRh1pkaw8',
    appId: '1:457325133463:ios:83afa2c97df21fc7b0f3d2',
    messagingSenderId: '457325133463',
    projectId: 'now-market-59841',
    storageBucket: 'now-market-59841.firebasestorage.app',
    iosBundleId: 'com.nowmarket.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu3YzMwetvXB-1JNB2kHdb8RaRh1pkaw8',
    appId: '1:457325133463:ios:6a36fed2f2297241b0f3d2',
    messagingSenderId: '457325133463',
    projectId: 'now-market-59841',
    storageBucket: 'now-market-59841.firebasestorage.app',
    iosBundleId: 'com.nmd.customer.customerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv9SMx7a_UI5feRfuDUwfamMm7Vxul6PQ',
    appId: '1:457325133463:web:d22a926ebdf65b22b0f3d2',
    messagingSenderId: '457325133463',
    projectId: 'now-market-59841',
    authDomain: 'now-market-59841.firebaseapp.com',
    storageBucket: 'now-market-59841.firebasestorage.app',
    measurementId: 'G-VGZ6NL1Z48',
  );
}
